Import('env', 'syms')

import os

schs = {}
for name in ['dimmer_shield', 'lumen_shield', 'led_mount']:
    pattern = os.path.join(name, '*.sch')
    schs[name] = env.Glob(pattern)
    env.Depends(schs[name], syms)

Return('schs')
